### PR TITLE
sixad: convert to systemd package & stretch compatibility

### PR DESCRIPTION
**Pull request by psyke83**
* checkinstall: use proper pre/post scripts to cleanup/configure
  daemon
* Remove all SysVinit support in place of systemd
* Instead of kill + chmod of bluetoothd, disable and stop bluetooth
  service when needed.
* Use --no-block flag to avoid service blocking caused by bluetooth
  stop/restart (issue present on stretch)

### CODE REVIEW

**Comment by joolswills** [comment]
>Despite my tests, I'd recommend you double-check. I'm not certain why the script opts to chmod + pkill bluetoothd instead of the simpler measure of stopping the bluetooth service on SysVinit.

Probably because the scripts are old and not written by us originally afaik, and may not be using the best methods. 

Is this PR complete as the CHMOD is still present etc, and that can be removed now ? Also the way we make bluetoothd executable again in RetroPie-Setup can be removed too once this is finalised. Disabling the service is a better way,

**Comment by psyke83** [comment]
I don't know if you want to keep sixad compatible with other distributions that don't have systemd.  I could drastically clean up the script and replace the init.d with sixad.service if you want - just let me know.

**Comment by joolswills** [comment]
I'm happy to move to systemd only - this repo is specifically for RetroPie and we don't support Wheezy. It's possible some people use it on Ubuntu 14.04, but we cannot really support old LTS releases of Ubuntu anyway due to manpower (Not sure if it works correctly anyway on Ubuntu).

As @gizmo98 has had more involvement than me with this repo though, I will let him decide as I may be wrong.

**Comment by psyke83** [comment]
OK. I'll update the patch to target systemd, so don't merge yet, please. Once that's done, we can ping @gizmo98 to ask if he's also happy with the result.

**Comment by psyke83** [comment]
PR updated to move over to systemd completely, ready to test. Confirmed working on both jessie and stretch, but would appreciate fresh eyes (if only for jessie, since stretch is not yet officially supported).

**Comment by psyke83** [comment]
The following PR is to complement the package change (not strictly necessary to test): https://github.com/RetroPie/RetroPie-Setup/pull/2158

**Comment by psyke83** [comment]
Did a small update to the PR. I previously removed the pkill commands from the --stop section, as systemd kills all child processes automatically. Killing the sixad shell script results in systemd reporting the service as failed, which is not what we want.

I change it so that it will pkill the binaries, and only pkill the shell script if the sixad service is not installed/running. This allows sixad start/stop to continue working in daemon mode without a service installed.

**Comment by gizmo98** [comment]
I will take a look next week. I have no PS3 Controller atm.

**Comment by joolswills** [comment]
If there are no objections I will merge this - @gizmo98 Let me know if you need more time.

**Comment by gizmo98** [comment]
Merge it. We can revert the commit if necessary.

**Comment by joolswills** [comment]
thanks.

**Comment by joolswills** [comment]
I have also applied these changes to the other branches - a user was reporting problems after updating which are probably related to the updates to retropie-setup whilst the other branches didn't contain the systemd updates.

**Pull request merged**
