### PR TITLE
sixad: set hci devices up/pscan if daemon starts

### PR DESCRIPTION
**Pull request by gizmo98**

### CODE REVIEW

**Comment by gizmo98** [comment]
@joolswills 
I have no right to commit directly to sixad and common-shaders?!

**Comment by gizmo98** [comment]
@joolswills 
Please add this commit to branch gasia as well

**Comment by joolswills** [comment]
I've added you to this repo now (I think). thanks.

**Comment by joolswills** [comment]
And you should have commit access on common-shaders too. cheers.

**Comment by gizmo98** [comment]
Thanks!

**Pull request merged**
