### PR TITLE
Pi3 hotfix

### PR DESCRIPTION
**Pull request by Dark-Show**
Attempt at fixing Bluetooth lockup on Sixaxis timeout.

### CODE REVIEW

**Comment by joolswills** [comment]
Please can you provide more information ? @gizmo98 - as you have been more involved in this than me - any feedback you have is welcome. Cheers.

**Comment by Dark-Show** [comment]
Been a while since I used RetroPie, updated to a pi3. When using ps3
controllers when the controller timeout kicks in the Bluetooth would lockup
and not allow any controllers to be connected until reboot. I believe this
is due to an updated bluez that requires the sockets connected to the
bluetooth hardware to be flushed and closed properly. After implementing
this patch the controllers work fine and Bluetooth stopped locking up. I've
heard word this this is for the other pi's as well but I named it pi3 at
the time because of my tests.

**Comment by joolswills** [comment]
ok. I will merge. thanks.

**Comment by Dark-Show** [comment]
Thank you, hopefully this fixes some problems until the merge into bluez. I
would like to have a small look into assisting in that as well. Do you guys
have a line of communication open? Forums or IRC?

**Comment by joolswills** [comment]
Some initial discussion is here - https://github.com/RetroPie/sixad/issues/9

**Comment by joolswills** [comment]
This doesn't build

```
sixad-sixaxis.cpp: In function ‘int main(int, char**)’:
sixad-sixaxis.cpp:391:25: error: too many arguments to function ‘int close(int)’
     close(csk, SHUT_RDWR); // Close socket.
                         ^
In file included from shared.h:21:0,
                 from sixad-sixaxis.cpp:18:
/usr/include/unistd.h:353:12: note: declared here
 extern int close (int __fd);
            ^
Makefile:18: recipe for target 'sixad_bins' failed
make: *** [sixad_bins] Error 1
/home/pi/RetroPie-Setup
/home/pi/RetroPie-Setup/tmp/build/ps3controller /home/pi/RetroPie-Setup
```

reverting for now.

**Comment by gizmo98** [comment]
Was bluez updated in the last months? I did not had any timeout lookup problem with raspbian jessie. But i have not updated my setup for a while.

**Comment by joolswills** [comment]
Just some patches in Feb / May

**Comment by gizmo98** [comment]
Interesting. My setup is not up to date but it is also not so old. ;-) 
I will keep an eye on it next time.

**Pull request merged**
